<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrohcpe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrohcpe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGrohcpe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGrohcpe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGrohcpe\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Grohcpe',
    'container.build_id' => 'd8205464',
    'container.build_time' => 1527665721,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrohcpe');
