<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKoia5hx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKoia5hx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKoia5hx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKoia5hx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKoia5hx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Koia5hx',
    'container.build_id' => 'e9b7b725',
    'container.build_time' => 1527604819,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKoia5hx');
